### ISSUE TITLE
大佬求助，重装很多次了依旧卡在这里

### ISSUE THREAD

**Issue by xiih** [jiangyuxiaoxiao/Hiyori#3]
![screenshot-1711010404264](https://github.com/jiangyuxiaoxiao/Hiyori/assets/60916261/2611e988-1dde-43a4-9a44-f2322d2b8547)
首页的文档好像也打不开（难道是域名到期了吗？）

**Comment by jiangyuxiaoxiao** [comment]
首页文档没有维护了，主要是我bot号全被封了所以不想弄了

**Comment by jiangyuxiaoxiao** [comment]
playwright这个包炸了，试试重装一下，参考https://playwright.dev/python/docs/intro

**Comment by xiih** [comment]
> playwright这个包炸了，试试重装一下，参考 https://playwright.dev/python/docs/intro
感谢指点，现已经成功运行起来了。另外对您的遭遇表示同情，万恶的tx QAQ
